title: Gabriel Nixon Raj
description: Fragility, Learning, and Decision Systems
url: https://gabrielnixon.github.io
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Collections (optional)
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope: { path: "" }
    values:
      layout: post
      toc: false
      nav: true
